In [1]:
# import the required packages/modules
import pandas as pd
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import graphviz

In [2]:
# load the dataset
df = pd.read_excel("Datasets\datakelulusanmahasiswa.xls")

In [3]:
# display dataframe info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NAMA              379 non-null    object
 1   JENIS KELAMIN     379 non-null    object
 2   STATUS MAHASISWA  379 non-null    object
 3   UMUR              379 non-null    int64
 4   STATUS NIKAH      379 non-null    object
 5   IPS 1             379 non-null    float64
 6   IPS 2             379 non-null    float64
 7   IPS 3             379 non-null    float64
 8   IPS 4             379 non-null    float64
 9   IPS 5             379 non-null    float64
 10  IPS 6             379 non-null    float64
 11  IPS 7             379 non-null    float64
 12  IPS 8             372 non-null    float64
 13  IPK               376 non-null    float64
 14  STATUS KELULUSAN  379 non-null    object
dtypes: float64(9), int64(1), object(5)
memory usage: 44.5+ KB

In [4]:
# remove rows which that contain empty cells
df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 369 entries, 0 to 378
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NAMA              369 non-null    object
 1   JENIS KELAMIN     369 non-null    object
 2   STATUS MAHASISWA  369 non-null    object
 3   UMUR              369 non-null    int64
 4   STATUS NIKAH      369 non-null    object
 5   IPS 1             369 non-null    float64
 6   IPS 2             369 non-null    float64
 7   IPS 3             369 non-null    float64
 8   IPS 4             369 non-null    float64
 9   IPS 5             369 non-null    float64
 10  IPS 6             369 non-null    float64
 11  IPS 7             369 non-null    float64
 12  IPS 8             369 non-null    float64
 13  IPK               369 non-null    float64
 14  STATUS KELULUSAN  369 non-null    object
dtypes: float64(9), int64(1), object(5)
memory usage: 46.1+ KB

In [5]:
# convert categorical data into numerical data
d = {'LAKI - LAKI': 0, 'PEREMPUAN': 1}
df['JENIS KELAMIN'] = df['JENIS KELAMIN'].map(d)
d = {'MAHASISWA': 0, 'BEKERJA': 1}
df['STATUS MAHASISWA'] = df['STATUS MAHASISWA'].map(d)
d = {'BELUM MENIKAH': 0, 'MENIKAH': 1}
df['STATUS NIKAH'] = df['STATUS NIKAH'].map(d)

In [6]:
# print dataset in string format
print(df.to_string())

                               NAMA  JENIS KELAMIN  STATUS MAHASISWA  UMUR  STATUS NIKAH  IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK  STATUS KELULUSAN
0                    ANIK WIDAYANTI              1                 1    28             0   2.76   2.80   3.20   3.17   2.98   3.00   3.03   0.00  3.07        TERLAMBAT
1           DWI HESTYNA PRIHASTANTY              1                 0    32             0   3.00   3.30   3.14   3.14   2.84   3.13   3.25   0.00  3.17        TERLAMBAT
2                MURYA ARIEF BASUKI              1                 1    29             0   3.50   3.30   3.70   3.29   3.53   3.72   3.73   0.00  3.54        TERLAMBAT
3                     NANIK SUSANTI              1                 0    27             0   3.17   3.41   3.61   3.36   3.48   3.63   3.46   0.00  3.41        TERLAMBAT
4                 RIFKA ISTIQFARINA              1                 1    29             0   2.90   2.89   3.30   2.85   2.98   3.00   3.08   0.00  3.09        TERLAMBAT
5                         SUHARYONO              0                 1    27             0   2.95   2.82   3.09   3.10   2.78   3.16   3.23   0.00  3.07        TERLAMBAT
6                  FARIKHATUN NAZLI              1                 0    26             0   2.76   3.14   2.60   2.95   3.23   3.33   3.30   3.30  3.06            TEPAT
7                     FIFI SUNALISA              1                 0    27             0   2.62   2.89   2.32   2.50   2.50   2.86   3.05   2.50  2.91            TEPAT
8                 HENDRIK MULIYANTO              1                 1    25             1   3.60   3.54   3.52   3.39   3.52   3.68   3.15   0.00  3.40        TERLAMBAT
9                 IMAM AGUNG RIBOWO              1                 1    28             0   2.71   2.55   1.77   2.11   1.93   2.13   1.78   0.20  2.20        TERLAMBAT
10                     IMAM SANTOSA              1                 1    27             0   3.14   3.46   3.40   3.43   3.27   3.15   3.81   4.00  3.44        TERLAMBAT
11                IRFAN EKO WAHYUDI              1                 1    32             0   2.67   2.30   1.57   1.44   1.58   1.68   1.13   0.94  2.40        TERLAMBAT
12                     IWAN HAMBALI              1                 1    26             0   2.57   2.82   2.20   2.45   2.10   2.42   1.00   1.42  2.45        TERLAMBAT
13                     M SYAIFULLAH              1                 1    31             0   2.71   3.00   2.65   2.27   2.13   3.34   2.50   0.00  2.57        TERLAMBAT
14               DIANA LAILY FITHRI              1                 0    26             0   3.24   3.38   3.44   3.30   3.56   3.45   3.35   3.35  3.45        TERLAMBAT
15                    DONNY PRABOWO              0                 0    27             0   2.86   2.86   2.45   1.86   3.19   3.14   2.98   2.00  3.04        TERLAMBAT
16                      EDI JATMIKO              1                 0    27             0   2.71   3.27   2.54   3.36   3.23   3.28   3.15   2.00  3.19        TERLAMBAT
17                      ADI SUBEKTI              0                 1    29             0   2.67   2.20   1.45   3.00   3.17   3.08   3.33   0.00  2.95        TERLAMBAT
18                     AHMAD IBROZI              0                 0    27             0   2.67   2.68   1.95   1.61   2.36   2.21   0.78   0.92  2.11        TERLAMBAT
20                    ANDI SUNARWAN              0                 1    28             0   3.00   3.33   2.88   2.80   3.36   3.07   3.43   4.00  3.29        TERLAMBAT
21                      ANNY AZIZAH              0                 1    26             0   3.12   3.23   2.96   3.00   3.31   3.00   3.08   3.00  3.19        TERLAMBAT
22               ARIEF PRAM WAHYUDI              0                 0    26             0   2.90   3.32   2.83   2.91   3.30   2.83   3.27   4.00  3.11        TERLAMBAT
23           DENNY SELA PUTROWIBOWO              0                 1    29             0   2.95   3.41   3.48   3.24   2.95   3.00   2.75   0.00  3.20        TERLAMBAT
24                MARTHINA FLAVERIA              0                 1    25             1   3.05   2.92   2.27   2.65   3.00   3.45   3.24   2.00  3.09        TERLAMBAT
25                     MASLUH JAMIL              0                 1    30             0   2.64   3.00   2.90   2.77   3.25   3.50   3.22   2.00  3.08        TERLAMBAT
26                      MURDIANTORO              0                 0    32             0   2.45   2.45   2.14   1.95   1.82   2.66   1.61   0.00  2.32        TERLAMBAT
27                     NAILI ROHMAH              1                 1    27             0   0.33   2.90   3.16   2.35   3.09   2.96   3.24   3.45  3.23        TERLAMBAT
28                   NASRUL SAFARAH              0                 0    27             0   3.33   3.63   3.29   3.89   3.60   3.13   3.35   3.35  3.52            TEPAT
29            NOOR KAMALUDDIN MALIK              0                 1    26             0   2.52   2.70   2.84   2.77   3.29   3.15   2.61   3.00  3.00        TERLAMBAT
30                  ROHANA MIRAWATI              0                 0    25             0   3.05   3.38   3.21   2.93   2.83   3.33   3.39   2.50  3.25            TEPAT
31              SANDY YUDHA NUGRAHA              0                 1    30             0   2.81   3.09   2.63   3.36   2.96   3.24   3.04   3.30  3.10        TERLAMBAT
32                  SISKA LIANAWATI              0                 0    32             0   2.52   2.75   2.25   2.50   2.64   2.87   3.20   2.00  2.86            TEPAT
33                 SRI MINUK ISWATI              0                 0    27             0   3.12   3.10   2.73   2.80   3.07   3.31   2.77   2.77  3.07            TEPAT
34          SUDANDING DWI SUPRABANA              0                 0    27             0   2.86   3.05   2.54   2.36   2.41   2.48   2.61   2.77  3.06        TERLAMBAT
35                        SUGIYANTO              0                 1    26             1   3.05   3.27   2.31   3.05   3.08   3.37   3.64   2.77  3.10        TERLAMBAT
36                  SUSI  HANDAYANI              0                 1    25             0   2.71   3.16   2.44   2.91   3.02   2.98   3.36   3.21  3.07            TEPAT
37                           SUTOPO              0                 1    50             1   2.88   3.32   2.48   3.27   3.29   3.47   3.36   2.00  3.16        TERLAMBAT
38              TOTOK ANTON ARIBOWO              0                 1    27             0   2.76   3.25   2.98   1.91   2.89   3.71   2.61   2.32  3.07        TERLAMBAT
39                      ADI DARMADI              0                 1    29             0   2.69   2.59   3.20   3.00   2.95   2.82   3.15   2.00  3.03        TERLAMBAT
40              EKO JAUHARI SAPUTRO              0                 1    30             0   2.29   3.09   3.20   2.74   2.65   2.37   2.83   3.00  2.96        TERLAMBAT
41                   HARMINTO MULYO              0                 1    28             0   2.71   2.59   3.09   1.76   3.06   2.77   3.66   3.22  3.09        TERLAMBAT
42                    HERI PURWANTO              0                 1    27             0   2.43   3.02   3.00   2.79   2.75   2.59   3.08   2.63  2.90        TERLAMBAT
43                  MIFTACHUR RIDHO              0                 1    27             0   2.88   2.59   2.82   3.05   2.65   3.03   3.30   2.00  3.03        TERLAMBAT
44                  TATIK HIKMAWATI              0                 1    29             0   2.07   2.59   2.59   2.48   2.52   2.89   3.04   3.00  2.77        TERLAMBAT
45                 USWATUN KHASANAH              0                 1    25             0   3.10   3.00   2.98   3.10   3.25   3.26   3.46   0.00  3.17        TERLAMBAT
46                        A SYAFI'I              0                 0    28             0   2.57   2.55   2.57   1.91   2.33   2.45   2.19   2.55  2.94        TERLAMBAT
47            ABDUL GHOFFAR ISMA'IL              0                 1    28             0   3.26   3.73   3.02   3.50   2.69   3.33   3.09   3.50  3.24            TEPAT
48                ACHMAD FAHMI AQWA              0                 1    32             0   2.71   2.89   2.75   3.18   3.19   3.22   3.73   0.00  3.20            TEPAT
49                     ADY PRASETIA              0                 1    27             0   1.90   1.91   1.59   1.28   1.37   2.83   2.20   2.70  2.66        TERLAMBAT
50                     AGUNG WIDODO              0                 1    29             0   2.24   1.68   2.45   1.59   1.45   1.95   1.79   2.30  2.14        TERLAMBAT
51                      AGUS SUSILO              0                 1    27             0   2.52   2.27   2.68   1.86   1.63   2.62   2.97   2.17  2.72        TERLAMBAT
52                  AGUS BUDI UTOMO              0                 1    26             0   2.86   2.80   2.20   2.14   2.20   2.86   2.64   1.10  2.91        TERLAMBAT
53                     AGUS RIYANTO              0                 1    27             0   2.76   3.09   2.58   2.73   2.90   3.42   2.87   0.88  3.05        TERLAMBAT
54                  ALINA INDRAWATI              1                 1    25             0   2.57   2.82   2.89   2.64   2.52   3.39   2.80   0.88  2.97        TERLAMBAT
55                    ANDY MAHENDRA              0                 1    28             0   2.14   1.55   2.03   2.27   1.70   2.70   1.57   1.75  2.31        TERLAMBAT
56              ARIEF IRFANDIANSYAH              0                 0    32             0   2.48   2.95   2.84   2.50   2.00   2.64   2.48   0.00  2.73        TERLAMBAT
57                   ARIEF SETIAWAN              0                 0    26             0   2.33   1.84   2.76   2.14   1.77   2.65   2.58   1.79  2.45        TERLAMBAT
58      BAGUS WIBOWO HERRU PRIHANTO              0                 1    26             0   2.10   2.50   3.02   2.85   2.02   2.25   2.60   1.79  2.85        TERLAMBAT
59               DEFI MAULA KHORIDA              1                 0    27             0   2.88   3.48   3.17   2.50   2.77   3.53   3.30   0.00  3.15            TEPAT
60              DEVI RIESTYANINGSIH              1                 1    27             0   2.81   3.11   3.19   3.08   2.88   3.69   3.12   0.00  3.27        TERLAMBAT
61              DIAH KUSUMANINGTYAS              1                 1    28             0   2.60   2.91   2.68   2.68   2.36   3.14   3.22   0.00  2.92        TERLAMBAT
62                    EDI HARIYANTO              0                 0    29             0   2.76   2.95   2.43   2.27   2.31   2.97   2.61   0.00  2.93        TERLAMBAT
63                      EDI PURNOMO              0                 0    25             0   2.86   3.43   2.92   2.82   2.27   2.97   2.36   0.88  2.90        TERLAMBAT
64                       EMA SYAROH              1                 0    32             0   3.02   3.63   3.42   3.37   3.15   3.27   3.63   0.00  3.36            TEPAT
65                     EMAN PRASOJO              0                 1    27             0   2.57   3.39   2.60   2.73   2.87   2.76   2.79   1.00  3.00        TERLAMBAT
66                         EMAWANTI              1                 0    27             0   3.31   3.60   3.67   3.57   3.56   3.87   3.78   0.00  3.60            TEPAT
67             ERFANA SETIYANINGRUM              1                 1    25             0   3.00   3.23   2.88   3.09   2.94   3.61   3.33   0.00  3.22        TERLAMBAT
68          FARCHAN NOVE INDRIYANTO              0                 0    30             0   2.48   2.48   2.23   2.09   1.45   2.42   2.05   2.58  2.63            TEPAT
69                 FITRIA HANDAYANI              1                 1    32             0   2.52   2.80   2.59   2.50   2.32   3.14   3.00   0.00  2.90        TERLAMBAT
70                 FITYATUN FATAYAH              1                 1    27             0   2.76   3.18   3.13   2.75   2.80   3.16   3.05   0.00  3.06        TERLAMBAT
71                          HAROZUM              1                 1    27             1   2.57   3.16   3.06   2.88   2.30   3.00   3.23   0.00  3.10        TERLAMBAT
72            HERMAWAN BUDI HARTONO              0                 1    26             0   2.60   3.32   3.44   2.79   2.57   3.00   3.26   1.00  3.16        TERLAMBAT
73                 HERU NOR RACHMAD              0                 1    50             0   2.67   2.18   2.00   2.32   2.05   2.38   1.63   1.44  2.32        TERLAMBAT
74                 INDRI ERNAMAWATI              1                 1    27             0   2.86   2.82   3.20   2.58   2.23   3.10   3.19   0.00  3.02        TERLAMBAT
75                IWAN SETYO ASMOKO              0                 1    29             0   3.00   3.50   2.69   2.36   2.16   2.55   1.91   0.00  2.67        TERLAMBAT
76                  KHAMIM MASYFU'I              0                 1    30             0   2.05   1.68   2.24   2.09   1.59   2.47   2.17   2.29  2.33        TERLAMBAT
77                  KOMARUDIN FARUQ              0                 1    27             0   2.55   2.30   2.02   2.32   2.05   2.95   2.64   1.46  2.63        TERLAMBAT
78                 LINA NAILAL MUNA              1                 1    27             0   3.24   3.58   3.25   3.43   3.33   3.70   3.23   0.00  3.42        TERLAMBAT
79           MEILINDA IKA WIJAYANTI              1                 0    25             0   2.07   2.70   2.32   2.36   1.98   2.47   1.86   1.20  2.38        TERLAMBAT
80                    MIFTAHUL HUDA              0                 0    28             0   2.76   3.11   2.75   2.59   2.63   2.86   2.74   0.00  2.90        TERLAMBAT
81                   MOCH LUTFIANTO              0                 0    26             0   2.90   3.55   3.38   3.54   3.23   3.39   3.53   0.00  3.39            TEPAT
82               MOCHAMAD IRWANSYAH              0                 0    31             0   2.76   1.09   2.29   0.95   1.53   2.38   1.11   0.00  1.71        TERLAMBAT
83          MOH ERIK CHANDRA IRVANA              0                 1    26             0   2.29   2.14   1.84   1.67   1.31   2.00   1.64   2.69  2.31        TERLAMBAT
84          MOKHAMAD ALEX KHOIRUDIN              0                 1    27             0   2.55   2.16   2.14   2.27   1.81   2.03   2.16   2.17  2.62        TERLAMBAT
85               MUCHAMMAD BAHRUDIN              0                 1    27             0   2.17   2.66   2.55   2.00   1.61   2.88   2.45   1.47  2.76        TERLAMBAT
86                   MUHAMMAD ABDUH              0                 0    29             1   2.83   3.61   3.18   3.23   3.02   3.20   3.18   0.00  3.30            TEPAT
87              MUHAMMAD ABDUL AZIS              0                 1    27             0   2.26   1.86   0.32   0.00   0.20   0.00   1.67   1.72  1.39        TERLAMBAT
88                  MUHAMMAD AMINAN              0                 0    27             0   2.38   2.70   3.02   3.00   3.26   3.00   0.62   0.35  2.63            TEPAT
89             MUHAMMAD YASIN YUSUF              0                 0    28             0   2.69   2.50   3.07   2.83   2.52   3.14   3.14   0.00  2.79        TERLAMBAT
90                  NISWATUL ALIYAH              1                 1    26             0   2.86   2.70   2.89   2.73   2.41   3.19   2.07   1.21  2.92        TERLAMBAT
91               NOOR MUHAMMAD AFIF              0                 1    29             0   2.33   2.75   2.36   2.18   1.73   2.64   2.25   2.28  2.49        TERLAMBAT
92              NOVAN AIS SETIANSAH              0                 1    25             0   2.45   1.43   2.16   0.27   0.44   1.28   0.66   0.29  1.82        TERLAMBAT
93           PUTRI KURNIA HANDAYANI              1                 0    32             0   3.24   3.83   3.65   3.61   3.69   3.73   3.70   0.00  3.63            TEPAT
94                     REZA PAHLEVI              0                 1    27             0   2.24   3.14   1.90   1.89   1.63   2.39   1.75   1.45  2.18        TERLAMBAT
95                     RINA WARDANI              1                 1    27             0   2.74   2.41   2.75   2.86   1.68   3.13   2.52   0.88  2.81        TERLAMBAT
96          ROFIDA RONING MAHANONDA              1                 1    26             0   2.31   2.77   2.64   2.82   2.75   3.06   2.97   3.50  2.71        TERLAMBAT
97               RUDIYANTI SETIASIH              1                 0    26             0   2.62   3.02   2.52   2.91   2.55   2.81   2.36   0.00  2.83        TERLAMBAT
98                SHOFIA NUR JAMILA              1                 0    29             1   2.67   2.89   2.66   2.45   2.05   2.66   1.67   1.20  2.53        TERLAMBAT
99               SIGIT SETYO ATMOKO              1                 0    25             0   2.74   3.00   2.98   2.86   2.61   2.43   2.48   0.93  2.74        TERLAMBAT
100                       SUGIYANTO              0                 0    30             0   2.45   3.11   2.98   2.32   2.92   3.08   2.69   1.33  2.92        TERLAMBAT
101                        SUMARLAN              0                 0    32             0   2.71   3.41   2.73   2.45   2.34   2.73   3.23   1.38  2.90        TERLAMBAT
102                          SUYONO              0                 0    27             0   3.43   3.56   3.55   3.67   3.35   3.66   3.60   0.00  3.59            TEPAT
103                 TAUFIK SETYAWAN              0                 1    27             0   2.57   2.91   2.70   2.73   2.25   3.15   2.24   2.90  2.98        TERLAMBAT
104                    TRI MULYANTO              0                 1    26             0   3.00   3.04   2.90   3.14   2.67   3.38   2.47   0.88  3.00        TERLAMBAT
105                          TUGIYO              0                 0    26             0   3.76   3.81   3.17   3.63   3.81   3.81   3.70   0.00  3.64            TEPAT
106                  TUTIK KHOTIMAH              1                 0    29             0   3.64   3.96   3.69   3.83   3.81   4.00   3.85   0.00  3.80            TEPAT
107              YUDA LINDA PRATIWI              1                 1    25             0   2.95   3.50   3.19   2.96   3.18   3.75   3.19   0.00  3.37        TERLAMBAT
108           YUSTINUS ARI SETIAWAN              0                 0    26             0   2.88   2.71   3.45   3.15   2.88   3.00   2.86   0.00  3.02        TERLAMBAT
109                DANNY NOVRIYANTO              0                 1    29             0   1.08   1.84   0.71   1.70   1.91   1.50   1.50   0.88  2.27        TERLAMBAT
110              PRATIWI PUJIASTUTI              1                 1    25             0   3.10   2.38   2.41   2.27   2.57   2.86   2.12   0.00  2.75        TERLAMBAT
111                    EDY KUSMANTO              1                 0    42             0   3.05   2.35   3.39   2.50   2.84   2.40   1.67   0.00  2.75            TEPAT
112                  LAILI QODRIYAH              1                 1    24             0   3.71   3.60   3.60   3.61   3.83   3.53   2.42   0.00  3.69            TEPAT
113                  SUGENG RIYANTO              0                 0    25             0   3.00   2.83   3.57   3.26   3.83   3.33   2.43   0.00  3.37            TEPAT
114                   GUNA SETIAWAN              0                 0    25             0   2.76   2.53   2.98   2.71   2.64   3.03   3.06   0.00  2.89            TEPAT
115                        MASYKURI              0                 1    30             0   3.07   2.90   3.58   2.79   2.58   3.00   1.39   1.25  3.04        TERLAMBAT
116                   MUTIARA FANNY              1                 0    25             0   2.64   2.25   2.36   2.23   2.27   2.75   2.43   0.00  2.64        TERLAMBAT
117                  HERU WIJAYANTO              0                 0    24             0   3.52   3.48   3.77   3.52   3.58   3.47   2.25   0.00  3.57            TEPAT
118             SYARIEF WIRA ADMAJA              0                 0    25             0   2.31   2.86   2.70   2.46   2.50   2.12   2.64   0.00  2.65        TERLAMBAT

In [7]:
# separate the target variable (Y) from the features (X)
X = df.values[:, 1:14]
Y = df.values[:, 14]

In [8]:
# split the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.2, 
                                                    random_state=100)

In [9]:
# create the decision tree model based on entropy
dt_entropy = DecisionTreeClassifier(criterion="entropy",
                                    random_state=100, 
                                    max_depth=4, 
                                    min_samples_leaf=1)

In [10]:
# perform the training
dt_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=100)

In [11]:
# visualize the decision tree
dot_data = export_graphviz(dt_entropy, out_file=None,
                           feature_names=df.columns[1:14],
                           class_names=['TEPAT', 'TERLAMBAT'],
                           filled=True, rounded=True, 
                           special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("Decision Tree")

'Decision Tree.pdf'

In [12]:
# prediction on data testing
y_pred = dt_entropy.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
['TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT'
 'TEPAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TEPAT'
 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT'
 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TEPAT'
 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT'
 'TERLAMBAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT'
 'TEPAT' 'TERLAMBAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT'
 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TERLAMBAT'
 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TERLAMBAT'
 'TEPAT']

In [13]:
# print the assessment of the model
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred, labels=['TEPAT', 'TERLAMBAT'])) 
print ("Accuracy : ", accuracy_score(y_test, y_pred)*100) 
print("Report : \n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[45  4]
 [ 4 21]]
Accuracy :  89.1891891891892
Report :
               precision    recall  f1-score   support

       TEPAT       0.92      0.92      0.92        49
   TERLAMBAT       0.84      0.84      0.84        25

    accuracy                           0.89        74
   macro avg       0.88      0.88      0.88        74
weighted avg       0.89      0.89      0.89        74

In [14]:
# import library to make gui in python
import tkinter as tk

In [15]:
def get_response(jk, sm, u, sn, ip1, ip2, ip3, ip4, ip5, ip6, ip7, ip8, ipk):
    if sm.lower() == "mahasiswa":
        sm = 0
    elif sm.lower() == "bekerja":
        sm = 1
    
    if sn.lower() == "belum menikah":
        sn = 0
    elif sn.lower() == "menikah":
        sn = 1

    prediction = dt_entropy.predict([[jk, sm, u, sn, ip1, ip2, ip3, ip4, ip5, ip6, ip7, ip8, ipk]])
    label_result.config(text=prediction)

In [16]:
# gui code program
HEIGHT = 500
WIDTH = 600

root = tk.Tk()

canvas = tk.Canvas(root, height=HEIGHT, width=WIDTH)
canvas.pack()

frame = tk.Frame(root, bg='#80c1ff')
frame.place(relwidth=1, relheight=1)

var = tk.IntVar()
label_jk = tk.Label(frame, text="Jenis Kelamin: ", bg='#80c1ff', font=('helvetica', 14), anchor='w')
label_jk.place(relwidth=0.2, relx=0, rely=0)

rb_jk1 = tk.Radiobutton(frame, text="Laki-laki", bg='#80c1ff', font=('helvetica', 14), variable=var, value=0)
rb_jk1.place(relx=0.2, rely=0)

rb_jk2 = tk.Radiobutton(frame, text="Perempuan", bg='#80c1ff', font=('helvetica', 14), variable=var, value=1)
rb_jk2.place(relx=0.35, rely=0)

label_sm = tk.Label(frame, text="Status Mahasiswa (Mahasiswa atau Bekerja): ", font=('helvetica', 10), bg='#80c1ff', anchor='w')
label_sm.place(relwidth=0.2, relx=0, rely=0.08)

entry_sm = tk.Entry(frame)
entry_sm.place(relwidth=0.2, relx=0.2, rely=0.08)

label_u = tk.Label(frame, text="Umur: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_u.place(relwidth=0.2, relx=0, rely=0.15)

entry_u = tk.Entry(frame)
entry_u.place(relwidth=0.2, relx=0.2, rely=0.15)

label_sn = tk.Label(frame, text="Status Nikah (Menikah atau Belum Menikah): ", font=('helvetica', 10), bg='#80c1ff', anchor='w')
label_sn.place(relwidth=0.2, relx=0, rely=0.23)

entry_sn = tk.Entry(frame)
entry_sn.place(relwidth=0.2, relx=0.2, rely=0.23)

label_ip1 = tk.Label(frame, text="IPS 1: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip1.place(relwidth=0.2, relx=0, rely=0.29)

entry_ip1 = tk.Entry(frame)
entry_ip1.place(relwidth=0.2, relx=0.2, rely=0.29)

label_ip2 = tk.Label(frame, text="IPS 2: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip2.place(relwidth=0.2, relx=0, rely=0.35)

entry_ip2 = tk.Entry(frame)
entry_ip2.place(relwidth=0.2, relx=0.2, rely=0.35)

label_ip3 = tk.Label(frame, text="IPS 3: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip3.place(relwidth=0.2, relx=0, rely=0.41)

entry_ip3 = tk.Entry(frame)
entry_ip3.place(relwidth=0.2, relx=0.2, rely=0.41)

label_ip4 = tk.Label(frame, text="IPS 4: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip4.place(relwidth=0.2, relx=0, rely=0.47)

entry_ip4 = tk.Entry(frame)
entry_ip4.place(relwidth=0.2, relx=0.2, rely=0.47)

label_ip5 = tk.Label(frame, text="IPS 5: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip5.place(relwidth=0.2, relx=0.6, rely=0)

entry_ip5 = tk.Entry(frame)
entry_ip5.place(relwidth=0.2, relx=0.7, rely=0)

label_ip6 = tk.Label(frame, text="IPS 6: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip6.place(relwidth=0.2, relx=0.6, rely=0.08)

entry_ip6 = tk.Entry(frame)
entry_ip6.place(relwidth=0.2, relx=0.7, rely=0.08)

label_ip7 = tk.Label(frame, text="IPS 7: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip7.place(relwidth=0.2, relx=0.6, rely=0.15)

entry_ip7 = tk.Entry(frame)
entry_ip7.place(relwidth=0.2, relx=0.7, rely=0.15)

label_ip8 = tk.Label(frame, text="IPS 8: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ip8.place(relwidth=0.2, relx=0.6, rely=0.23)

entry_ip8 = tk.Entry(frame)
entry_ip8.place(relwidth=0.2, relx=0.7, rely=0.23)

label_ipk = tk.Label(frame, text="IPK: ", font=('helvetica', 14), bg='#80c1ff', anchor='w')
label_ipk.place(relwidth=0.2, relx=0.6, rely=0.29)

entry_ipk = tk.Entry(frame)
entry_ipk.place(relwidth=0.2, relx=0.7, rely=0.29)

button = tk.Button(frame, text="Get Prediction", font=('helvetica', 14), command=lambda: get_response(var.get(), entry_sm.get(), entry_u.get(),
                                                                          entry_sn.get(), entry_ip1.get(), entry_ip2.get(), 
                                                                          entry_ip3.get(), entry_ip4.get(), entry_ip5.get(), 
                                                                          entry_ip6.get(), entry_ip7.get(), entry_ip8.get(), 
                                                                          entry_ipk.get()))
button.place(relx=0.45, rely=0.6)

label_result = tk.Label(frame, bg='#80c1ff', font=('helvetica', 16, 'bold'))
label_result.place(relx=0.46, rely=0.8)

root.mainloop()